### PR TITLE
Break lines into smaller statements. Add annotation. Add sql to create t...

### PR DESCRIPTION
**Pull request by johnstile**
Break lines into smaller statements. Add annotation. Add sql to create the table if it does not exist.

### CODE REVIEW

**Comment by robbintt** [comment]
Hey John - can you update lines 65 and 66 to use `logging.debug(thingy)` rather than using the multiline `if debug: \ print thingy` pattern?

**Comment by robbintt** [comment]
Typo `excdept` was introduced on line 98.

**Comment by robbintt** [comment]
Typo `hangle` on comment line 194.

**Comment by robbintt** [comment]
on line 206-208 switch to using logging.debug as well. no need for the debug flag although I can see times when it could be useful.

**Comment by robbintt** [comment]
That's all I see! Once those updates are in I'll give it a final once over again. Thanks for pushing some changes by the way, I really like how it cleans things up and makes the places where we can dry the code out more apparent.

**Comment by johnstile** [comment]
didn't see your feedback until I committed the expantion of the logging facility.  Not sure if I went too far.  I did apply the changes.  Do you want me to pull it out?

**Comment by robbintt** [comment]
Neat, can you break then new logging stuff/factory another file and import it like a module? 

You can put it in a utils/ folder.

What I want to remove is the debug flag and associated print functionality, instead relying on logging.debug() in these instances. The code should be free of print statements unless they belong in production for user purposes.

Looks neat, I'll read the log factory soon!

**Comment by johnstile** [comment]
utils directory added.  log module created.   print removed from testdata.py.
What do you think?

**Comment by robbintt** [comment]
Looking great, one sticky wicket in the import, can you add a __init__.py and use the normal `import utils/log' pattern?

**Comment by robbintt** [comment]
I'm still thinking we should replace all the print statements in the utils/log module with log.debug(mystatement). What do you think?

**Comment by robbintt** [comment]
The two print statements I am referring to are the ones that say whether or not a logging directory is being created, seems like those belong in debug since if logging is escalated we don't want to see them.

I believe the other two statements are statements intended to be a permanent part of the user's experience.  I see the last one is for your debug flag though so I don't see any reason to take it out. People can experiment with it.

**Comment by johnstile** [comment]
Print is basicly replaced by the use of the logger module.  But if there is some issues, it would be handy if a facility (e.g. print) could show where things failed. The only time print is used is when debug = 1.  Do you still want all prints removed?

**Comment by robbintt** [comment]
Looks good, I am ready to pull this as soon as you have the import statement updated to follow the pattern `import utils/log` rather than using the os module (unless there's some reason to do it that way that I am unaware of).

**Comment by johnstile** [comment]
utils directory right next to testdata.py, but where I work, our 'utils' could have a very differnt path in the repo, so being able to handle another path is very handy.  My understanding is a pythonic way to handle this is using the platform independent os.path.join().  Shouldn't this code also work on Windows?

**Comment by robbintt** [comment]
I see what you mean, but in this case we are hardcoding the relative path of utils in the repo. In other words, we expect people to leave `utils/log.py` as the relative path from our application or change it themselves if they need the increased flexibility.

**Comment by robbintt** [comment]
I made a typo above (haven't read about this in awhile) - Python supports a binding syntax for imports using directories, which is pretty nice.  Here's an example: https://github.com/scrapy/scrapy/blob/master/scrapy/log.py. So the actual line would be `import utils.log`.  Here's a not totally on topic stackexchange discussing a simiilar but ultimately unrelated issue regarding import paths. It has good examples of the dot notation: https://programmers.stackexchange.com/questions/159503/whats-wrong-with-relative-imports-in-python

**Comment by johnstile** [comment]
Nice.  I didn't know about that. Change is made

**Comment by robbintt** [comment]
Merged. Looks great!

**Pull request merged**
